# Generated by Django 6.0 on 2025-12-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(choices=[('Code2', 'Code'), ('PenTool', 'Design'), ('Database', 'Database'), ('LineChart', 'Marketing'), ('Video', 'Media'), ('Cpu', 'Hardware'), ('Globe', 'Web'), ('Smartphone', 'Mobile'), ('Cloud', 'Cloud'), ('Lock', 'Security')], default='Code2', max_length=50, verbose_name='Biểu tượng'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('red', 'Red'), ('yellow', 'Yellow'), ('teal', 'Teal')], default='blue', max_length=50, verbose_name='Màu sắc'),
        ),
    ]
