# Generated by Django 6.0 on 2025-12-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_icon_alter_topic_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='Code2', max_length=50, verbose_name='Biểu tượng'),
        ),
    ]
